### PR TITLE
Update appspec.json

### PR DESCRIPTION
**Pull request by andreakoelzsch**
correct your path to readme

### CODE REVIEW

**Comment by CodenameGreyFox** [comment]
Sorry. I accepted the merge. Should I put a new version in MoveApps?

**Comment by andreakoelzsch** [comment]
yes, I am just writing to you about it. please a new moveApps version, else it is difficult to find hte documentation for hte reviewers. sorry that I didnt see that before. Thanks!

**Comment by CodenameGreyFox** [comment]
Done!

**Comment by andreakoelzsch** [comment]
thanks, and it is also built and works!

**Pull request merged**
